version: '3.7'

services:
  nginx:
    build: .
    container_name: nginx
    restart: always
    ports:
      - 80:80
    # volumes:
    # - ./conf/nginx.conf:/etc/nginx/nginx.conf
    #  -  ./src/main/resources/static:/usr/share/nginx/html
    # - ./maven-data/app/src/main/webapp:/usr/share/nginx/
    # - ./maven-data/app/src/main/webapp/setup/index.html:/usr/share/nginx/index.html
    networks:
    - subnet
    depends_on:
      - ted_app
  ted_app:
    image: 644435390668.dkr.ecr.eu-west-2.amazonaws.com/piotrekcowsay:latest
    container_name: cow
    ports:
      - 5000:8081
    networks:
      - subnet
networks:
  subnet:
    name: subnet