version: '3.7'
services:
  nginx:
    build: .
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
    - cert:/etc/letsencrypt:rw
    networks:
    - subnet
    depends_on:
      - ted_app
  ted_app:
    image: 644435390668.dkr.ecr.eu-west-2.amazonaws.com/piotrekcowsay:latest
    container_name: cow
    ports:
      - 5000:8081
    networks:
      - subnet
networks:
  subnet:
    name: subnet
volumes:
  cert: